CLI Auth Compatibility
roboflow/roboflow-python pull request #62
Opened 2022-10-05 15:46 UTC by Jacobsolawetz

# Description

This PR adds CLI auth compatibility

We check for configuration from:

1) env vars
2) CLI config
3) defaults

It is compatible with the old `Roboflow(api_key="")` and now a new `Roboflow()` object

You can test functionality with the CLI `roboflow auth` and then

```
from roboflow import Roboflow

rf = Roboflow()
```

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini reviewed
Left some comments :)

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/__init__.py
> +                api_key = RF_API_KEY
not 100% correct, should be checked by `is not None`

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/__init__.py
> +        if api_key == None:
same

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/__init__.py
> +            raise(RuntimeError("You must provide an api_key on init or use the Roboflow CLI to authenticate"))
```suggestion
raise RuntimeError("You must provide an api_key on init or use the Roboflow CLI to authenticate")
```

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/config.py
> +)
you can use `pathlib` that is compatible across different platforms (linux, osx, windows)

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/config.py
> +if RF_WORKSPACE == None:
same as above

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/config.py
> +    if os.getenv(key) != None:
same as above

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/config.py
> +        config = json.load(f)
I think we should validate the config json file, having a class will help

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/config.py
> +def get_var_conditional(key, default):
maybe a little docstring explain what this bad boy does :)

2022-10-06 14:26 UTC, FrancescoSaverioZuppichini commented on roboflow/config.py
> +if os.getenv("RF_API_KEY") != None:
same as above

2022-10-06 15:14 UTC, broox commented
dangit. i left a bunch of feedback on the wrong PR i think, haha. you can see those comments here: https://github.com/roboflow-ai/roboflow-python/pull/61

2022-10-10 11:39 UTC, FrancescoSaverioZuppichini requested changes
See comment

2023-02-06 09:59 UTC, FrancescoSaverioZuppichini commented
@Jacobsolawetz what's the status of this PR?

2023-03-14 14:23 UTC, Jacobsolawetz commented
Closing since this was absorbed in quickstart backbones

2023-03-14 14:23 UTC, closed without merging