Add version training support
roboflow/roboflow-python pull request #74
Opened 2022-11-07 14:38 UTC by broox

# Description

This adds support for the new Roboflow train API, allowing python package users to programmatically train a dataset version.

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [*] New feature (non-breaking change which adds functionality)
-   [*] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Unit tests

## Any specific deployment considerations

We should document this new functionality!

## Docs

-   [ ] Docs updated? What were the changes:

2022-11-07 14:44 UTC, broox commented on roboflow/core/version.py
> +            HTTPError: If the Network/Roboflow API fails and does not return JSON
while i was in here, i decided to also update the existing docstrings to the preferred style.
`¯\_(ツ)_/¯`

2022-11-07 14:44 UTC, broox commented on roboflow/core/workspace.py
> +from roboflow.util.active_learning_utils import check_box_size, count_comparisons
`make style` did this.

2022-11-07 14:44 UTC, broox commented on roboflow/models/object_detection.py
> +        if hasattr(image_path, "__len__"):
`make check_code_quality` caught this. not sure how it got in before!

2022-11-07 14:44 UTC, broox commented on roboflow/util/clip_compare_utils.py
> -import glob
`make style` caught this

2022-11-22 09:54 UTC, FrancescoSaverioZuppichini commented on roboflow/core/version.py
> +            Dataset
This will be never parsed, need to specify where it comes from (the module path)

2022-11-22 09:55 UTC, FrancescoSaverioZuppichini commented on roboflow/core/version.py
> +            True
wrong, should be the type

2022-11-22 09:55 UTC, FrancescoSaverioZuppichini commented on roboflow/core/version.py
> +            True
same here

2022-11-22 09:55 UTC, FrancescoSaverioZuppichini commented on roboflow/core/version.py
> +            local path string
wrong

2022-11-22 09:56 UTC, FrancescoSaverioZuppichini requested changes
The whole docstring is wrong, please follow the [google one](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)

2022-12-30 15:08 UTC, Jacobsolawetz commented
Subsumed in https://github.com/roboflow/roboflow-python/pull/89

2022-12-30 15:08 UTC, closed without merging